<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Dapper" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\BuildingBlocks\BookingSystem.EntityFrameworkCore\BookingSystem.EntityFrameworkCore.csproj" />
        <ProjectReference Include="..\..\..\BuildingBlocks\BookingSystem.SharedKernel\BookingSystem.SharedKernel.csproj" />
        <ProjectReference Include="..\BookingSystem.Cinema.Application\BookingSystem.Cinema.Application.csproj" />
        <ProjectReference Include="..\BookingSystem.Cinema.Domain\BookingSystem.Cinema.Domain.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Folder Include="Persistence\Migrations\" />
        <Folder Include="Services\" />
    </ItemGroup>
</Project>
