<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\..\..\BuildingBlocks\BookingSystem.SharedKernel\BookingSystem.SharedKernel.csproj" />
        <ProjectReference Include="..\BookingSystem.Order.Domain\BookingSystem.Order.Domain.csproj" />
    </ItemGroup>
</Project>
