<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <ProjectReference Include="..\..\..\BuildingBlocks\BookingSystem.SharedKernel\BookingSystem.SharedKernel.csproj" />
        <ProjectReference Include="..\BookingSystem.Cinema.Domain\BookingSystem.Cinema.Domain.csproj" />
    </ItemGroup>
</Project>
